enum csowtypes_e
{
	TYPE_PRIMARY = 0,
	TYPE_SECONDARY,
	TYPE_MELEE,
	TYPE_GRENADE
};

enum eBulletType
{
	BULLET_PLAYER_45ACP = 18,
	BULLET_PLAYER_50AE,
	BULLET_PLAYER_762MM,
	BULLET_PLAYER_556MM,
	BULLET_PLAYER_338MAG,
	BULLET_PLAYER_57MM,
	BULLET_PLAYER_357SIG,
	BULLET_PLAYER_CSOBOW,
	BULLET_PLAYER_FAILNAUGHT
};

enum eTrailType
{
	TRAIL_NONE = 0,
	TRAIL_CSOBOW,
	TRAIL_FAILNAUGHT
};

enum SMOKETYPE
{
	SMOKE_RIFLE = 0,
	SMOKE_AUGEX,
	SMOKE_WALL1,
	SMOKE_WALL2,
	SMOKE_WALL3,
	SMOKE_WALL4
};